from turtle import*
from time import*
screensize(800,600,"green")
write('C站重要人物',font=['黑体',40,'normal'])
sleep(2)
clear()
write('看看有没有你哦',font=['黑体',40,'normal'])
sleep(2)
clear()
write('都是并列第一哦',font=['黑体',40,'normal'])
sleep(2)
clear()
write('严子昱',font=['黑体',40,'normal'])
sleep(1)
clear()
write('小饼干',font=['黑体',40,'normal'])
sleep(1)
clear()
write('李伟',font=['黑体',40,'normal'])
sleep(1)
clear()
write('贺人杰',font=['黑体',40,'normal'])
sleep(1)
clear()
write('吉吉国王',font=['黑体',40,'normal'])
sleep(1)
clear()
# 上面5个
write('王玎珰',font=['黑体',40,'normal'])
sleep(1)
clear()
write('胡锦辉',font=['黑体',40,'normal'])
sleep(1)
clear()
write('郭昀峰',font=['黑体',40,'normal'])
sleep(1)
clear()
write('欧卓元',font=['黑体',40,'normal'])
sleep(1)
clear()
write('猫博士',font=['黑体',40,'normal'])
sleep(1)
clear()
# 5个
write('小星星',font=['黑体',40,'normal'])
sleep(1)
clear()
write('吴振发',font=['黑体',40,'normal'])
sleep(1)
clear()
write('林圣杰',font=['黑体',40,'normal'])
sleep(1)
clear()
write('这个神秘人',font=['黑体',40,'normal'])
sleep(1)
clear()
write('终端见',font=['黑体',40,'normal'])
sleep(1)
clear()
print('''
小轩
身份：
宇宙工作室室长
A字团队团长
jhx团队团长
地球捍卫队队长
蓝桥杯一等奖之人
tcty98分3级之人
2020/1/9
想知道更多，回复！''')