from turtle import*;from random import*;from time import sleep as s;Screen().bgcolor('black')
a = print
a('666')
speed(0)
for i in range(50):
    pu()
    goto(randint(-300,300),randint(0,250))
    color(choice(['red','yellow','green','blue','white','brown','purple']))
    begin_fill()
    circle(randint(5,25),720,5)
    end_fill()
goto(0,-100)
color('white')
pd()
write('小轩的作品',font = ['楷体',30,'normal'])
for i in range(10):
    s(0.65)
    clear()
    color('black')
    Screen().bgcolor('white')
    write('小轩的作品',font = ['楷体',30,'normal'])
    s(0.65)
    clear()
    color('white')
    Screen().bgcolor('black')
    write('小轩的作品',font = ['楷体',30,'normal'])
    hideturtle()
s(3)