print('\033[1;33m还真有人举报我，但是没人想到它会自动复原。\033[0m')
from time import *
print('小白总是一窝脑的喷我')
sleep(0.1)
print('从今天开始，我再也不手下留情了')
sleep(0.1)
print('喷我的评论置之不理，全删')
sleep(0.1)
print('多次喷我的人，想各种办法让ta退站')
sleep(0.1)
print('此作品不准举报。举报一次发一次。')
sleep(0.1)
print('不准违反上面的。')
sleep(0.1)
print('\033[1;31m如 ',end='')
sleep(0.4)
print('果 ',end='')
sleep(0.4)
print('有 ',end='')
sleep(0.4)
print('人 ',end='')
sleep(0.4)
print('违 ',end='')
sleep(0.4)
print('反 ',end='')
sleep(0.4)
print('，，',end='')
sleep(1.1)
print('你们应该知道的',end='')
sleep(0.4)
print()
print('后果自负！！！！！')