from CloudDB import *
print("CloudDB的数据存储方式比较特殊,不是普通的列表、字典、元组,而是以一种和Excel表格十分接近的形式进行增删改查,有两个关键的值,x的值为字符串,表示列,y的值为整数,表示行")
print("这种特殊的数据类型我写成了一个单独的类,叫做IXDB,意思大家应该都比较清楚,就是IdealXes DataBase(IdealXes数据库)的意思")
print("我认为这样类表格的存储方法比JSON更加灵活,更加稳定,拓展性更强")
print("调用示例:")
print("from CloudDB import * #导入库")
print("db = IXDB('db') #创建数据库")
print("cdb = CloudDB(projectid,userid) #创建云数据库")
print("cdb.open('data') #开启云数据库连接")
print("cdb.create(db) #创建云数据库,并与数据库db绑定")
print("cdb.add(1,[1,2,3,4,5],'key') #添加一列数据,该列的键为key,一共五行")
print("cdb.push() #推送数据")
print("cdb.pull() #拉取数据")
print("cdb.remove(1,x = 'key') #删除键为key的一列")
print("cdb.query('key',0) #查询key列0行的数据")
print("cdb.close() #关闭连接")