from tkinter import *
root = Tk()
def a():
    print("~被调用了~")
e = Text(root,width=20,height=5)
e.pack()
b = Menu(root)
c = Menu(b,tearoff=True)
e.insert(INSERT,"")
c.add_command(label="打开",command=a)
c.add_command(label="保存",command=a)
c.add_separator()
c.add_command(label="退出",command=root.quit)
b.add_cascade(label="文件",menu=c)
d = Menu(b,tearoff=True)
d.add_command(label="剪切",command=a)
d.add_command(label="拷贝",command=a)
d.add_separator()
d.add_command(label="粘贴",command=a)
b.add_cascade(label="编辑",menu=d)
root.config(menu=b)
mainloop()