from time import *
from f import *
from a import *
from webbrowser import open as o
input('请取消点赞看到快结束了再点，还有，留意窗口的同时留意终端，看完回车哟~')
a1 = 喜欢('https://code.xueersi.com/home/project/detail?lang=code&pid=14227098&version=offline&form=python&langType=python')
print('你想知道封面之父是谁吗？')
sleep(1)
print('那我告诉你……算了，我们先来看几张图片！')
sleep(2)
print('首先，看看我的发布时间，看完关掉')
sleep(2.2)
ff('1.png')
ff('2.png')
print('再看看氵王的证据和评价')
sleep(1)
ff('3.png')
print('或者小茗的评价')
sleep(1)
ff('4.png')
print('恶毒者的评价（这人的粉丝数是多少？）')
sleep(1)
ff('5.png')
ff('6.png')
print('人生，总是那么不公平。精选的作品80%都很烂')
print('现在，你还想举报此作品吗？')
print('啊？🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬')
print('🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬')
print('我现在也不是特别喜爱这个大家庭了！也不喜欢秃头了！')
sleep(3)
print('我都有退站的念头了！')
print('都是泪啊！')
print('现在满大街都是这种格式！')
print('却不写原创!!！')
print('难道这不就是一种抄袭吗？！好好反思啊！')
print('你们…………你们（作者气炸）……是这种格式的标上封面之父————小轩！！！！！')
print('虽然我很生气，但是我对你们还是这么好：下几个作品里有作品全面剖析器，比星光厉害！（api##的找到累死，分割字符串真不好使，Google翻译搞成崩溃！）')
while True:
    input('请点赞把我点上去，点赞好了回车！会有彩蛋！{保证不骗赞}')
    a2 = 喜欢('https://code.xueersi.com/home/project/detail?lang=code&pid=14227098&version=offline&form=python&langType=python')
    if a2 <= a1:
        print('别骗人了，我的爬虫知道你没点赞')
    else:
        print('谢谢你，彩蛋开始')
        sleep(1)
        o('https://code.xueersi.com/home/project/detail?lang=code&pid=12817956&version=offline&form=python&langType=python')