import turtle
t = turtle.Turtle()
t.speed(10)

t.penup()
t.speed(5)
t.setheading(180)
t.forward(40)
t.setheading(90)
t.forward(255)
t.pendown()
t.setheading(-90)
t.pensize(5)
t.pencolor('DarkOrange4')
t.forward(450)
t.penup()


t.penup()
t.goto(-40.00, -190)
t.pendown()
t.pencolor('DarkOrange4')
t.pensize(3)
t.fillcolor('lightgoldenrodyellow')
t.begin_fill()
t.setheading(0)
t.forward(8)
t.setheading(60)
for i in range(1, 7):
        t.forward(3)
        t.right(9)
for i in range(1, 4):
        t.forward(4)
        t.right(4)
        t.penup()
t.goto(-30.00, -190.00)
t.pendown()
t.setheading(-30)
for i in range(1, 5):
    t.forward(3)
    t.left(12)
t.setheading(60)
for i in range(1, 4):
        t.forward(2)
        t.right(10)
t.penup()
t.goto(-18.58, -193.43)
t.pendown()
t.setheading(0)
t.forward(4)
for i in range(1, 4):
        t.forward(3)
        t.left(9)
for i in range(1, 3):
        t.forward(3)
        t.left(9)
t. penup()
t.goto(-5.76, -192.03)
t.pendown()
t.setheading(-40)
for i in range(1, 3):
        t.forward(1)
        t.left(20)
t.forward(8)
t.setheading(10)
for i in range(1, 9):
        t.forward(3)
        t.left(7)
t.setheading(70)
t.forward(25)
t.circle(25, 15)
t.setheading(95)
t.forward(35)
t.circle(-18, 25)
t.setheading(85)
t.forward(30)
for i in range(1, 21):
        t.forward(5)
        t.left(7)
t.end_fill()
t.penup()
t.goto(-32.00, -190.00)
t.pendown()
t.begin_fill()
t.setheading(60)
for i in range(1, 7):
        t.forward(3)
        t.right(9)
for i in range(1, 4):
        t.forward(4)
        t.right(4)
t.end_fill()
t.penup()
t.goto(-27.00, -187.50)
t.pendown()
t.pencolor('lightyellow')
t.pensize(4.5)
t.goto(-5.00, -180.0)
t.penup()


t.goto(-40, 100)
t.pencolor('saddlebrown')
t.fillcolor('lightyellow')
t.begin_fill()
t.pendown()
t.setheading(15)
t.forward(13)
t.pencolor('saddlebrown')
t.setheading(-100)
t.pensize(3)
t.forward(10)
t.goto(-27.44, 103.36)
t.setheading(70)
t.pencolor('saddlebrown')
for i in range(4):
        t.forward(15)
        t.right(5)
for i in range(3):
        t.forward(17)
        t.right(8)
t.setheading(-45)
t.forward(3)
t.setheading(-100)
t.forward(15)
for i in range(8):
        t.right(1)
        t.forward(1)
t.setheading(-108)
t.forward(20)
for i in range(3):
        t.forward(19)
        t.right(9)
t.pencolor('saddlebrown')
t.forward(8)
t.penup()
t.goto(3.46, 96.21)
t.pendown()
t.pensize(4)
t.setheading(-10)
t.forward(15)
t.pensize(3)
t.circle(-40, 30)
t.pensize(4)
t.forward(10)
t.pensize(3)
t.circle(30, 20)
for i in range(5):
        t.forward(1.5)
        t.left(2)
t.pensize(2)
t.setheading(0)
t.forward(5)
t.pensize(3)
t.setheading(-160)
t.circle(-80, 10)
t.pensize(2)
t.forward(4)
t.penup()
t.left(180)
t.forward(4)
t.pendown()
t.setheading(-30)
t.pensize(3)
t.forward(20)
t.circle(-1, 140)
t.forward(8)
t.setheading(-30)
t.pencolor('saddlebrown')
t.circle(-20, 45)
t.penup()
t.pencolor('saddlebrown')
t.goto(61.53, 54.30)
t.pendown()
t.setheading(10)
t.pensize(4)
t.forward(50)
for i in range(5):
        t.forward(10)
        t.right(3)
t.setheading(-10)
t.pensize(3)
for i in range(9):
        t.forward(1.5)
        t.right(20)
t.left(55)
t.circle(-90, 30)
t.circle(-120, 25)
t.setheading(110)
t.pensize(1)
t.forward(3)
t.pensize(4)
t.setheading(-80)
t.forward(25)
for i in range(10):
        t.forward(2)
        t.right(2)
for i in range(5):
        t.forward(3)
        t.right(3)
t.forward(40)
t.circle(-20, 60)
t.circle(-10, 40)
t.left(25)
t.forward(64.91)
t.end_fill()
t.penup()


t.penup()
t.pencolor('saddlebrown')
t.fillcolor('chocolate')
t.goto(-40.00, -110.00)
t.pendown()
t.begin_fill()
t.setheading(20)
for i in range(1, 7):
        t.forward(9)
        t.left(7)
for i in range(1, 4):
        t.forward(10)
        t.left(13)
t.setheading(120)
for i in range(1, 7):
        t.forward(5)
        t.left(13)
for i in range(1, 7):
        t.forward(5)
        t.left(5)
t.end_fill()
t.penup()
t.goto(-40.00, -103.00)
t.pendown()
t.fillcolor('sandybrown')
t.begin_fill()
t.setheading(24)
for i in range(1, 7):
        t.forward(9)
        t.left(7)
for i in range(1, 4):
        t.forward(9)
        t.left(13)
t.setheading(120)
for i in range(1, 5):
        t.forward(5)
        t.left(19)
for i in range(1, 7):
        t.forward(5)
        t.left(5)
t.end_fill()
t.penup()


t.penup()
t.goto(-27.44, 103.36)
t.fillcolor('saddlebrown')
t.setheading(70)
t.pencolor('saddlebrown')
for i in range(3):
        t.forward(15)
        t.right(5)
t.begin_fill()
for i in range(1):
        t.forward(15)
        t.right(5)
for i in range(3):
        t.forward(17)
        t.right(8)
t.setheading(-45)
t.forward(3)
t.setheading(-100)
t.forward(15)
for i in range(8):
        t.right(1)
        t.forward(1)
t.setheading(-108)
t.forward(20)
for i in range(1):
        t.forward(19)
        t.right(9)
t.setheading(95)
t.circle(60, 20)
t.circle(10, 70)
t.end_fill()
t.penup()


t.goto(61.53, 54.30)
t.pendown()
t.setheading(10)
t.pensize(4)
t.forward(50)
t.fillcolor('saddlebrown')
t.begin_fill()
for i in range(5):
        t.forward(10)
        t.right(3)
t.setheading(-10)
for i in range(9):
        t.forward(1.5)
        t.right(20)
t.left(55)
t.circle(-90, 30)
t.circle(-120, 7)
t.setheading(60)
t.circle(40, 30)
t.circle(15, 40)
t.penup()
t.end_fill()


t.penup()
t.goto(16, -80)
t.pencolor('sienna')
t.pensize(3)
t.fillcolor('lightyellow')
t.pendown()
t.begin_fill()
t.setheading(100)
t.forward(10)
t.circle(10, 30)
t.forward(15)
t.circle(10, 40)
t.forward(10)
t.setheading(300)
t.forward(5)
t.setheading(170)
t.forward(7)
t.setheading(280)
t.forward(7)
t.setheading(170)
t.forward(5)
t.setheading(250)
t.forward(7)
for i in range(1, 6):
    t.forward(0.5)
    t.left(10)
t.setheading(-70)
t.forward(15)
t.circle(30, 10)
for i in range(1, 5):
    t.forward(7)
    t.left(4)
t.end_fill()
t.pendown()


t.penup()
t.goto(2, -15)
t.pendown()
t.pencolor('sienna')
t.dot(4)
t.penup()



t.goto(-38, 10)
t.setheading(45)
t.pendown()
t.begin_fill()
t.pencolor('darkred')
t.fillcolor('saddlebrown')
t.circle(50, 30)
t.circle(7, 170)
t.end_fill()
t.goto(-34, 39)
t.pencolor('lightyellow')
t.dot(5)
t.penup()
t.goto(-50, 100)

t.penup()
t.pencolor('darkred')
t.goto(45, -35)
t.pendown()
t.setheading(50)
t.begin_fill()
t.fillcolor('saddlebrown')
t.circle(50, 30)
t.circle(6, 170)
t.right(25)
t.circle(50, 25)
t.circle(7, 30)
t.circle(6, 35)
t.circle(7, 45)
t.goto(45, -35)
t.end_fill()
t.penup()
t.goto(45, -9)
t.pendown()
t.pencolor('lightyellow')
t.dot(5)
t.penup()
t.hideturtle()
turtle.mainloop()