import pygame,sys,os
pygame.init()
screen = pygame.display.set_mode((800, 600))
pygame.display.set_caption("下山")
xiashan = pygame.image.load("下山.PNG")
xiashan = pygame.transform.scale(xiashan,(800,600))
music = pygame.mixer.music.load("下山.mp3")
pygame.mixer.music.play(-1)
print("\033[1;35m一首《下山》送给你，望你喜欢。")
print("歌词献上：")
print("\033[1;32m要想练就绝世武功")
print("就要忍受常人难忍受的痛")
print("师傅喜欢喝的茶叫做乌龙")
print("衣服爱穿中国红 嘿 师傅")
print("无论是炎夏或寒冬")
print("我都很向往山门外的天空")
print("还在南方等我 下山的我")
print("的人叫小落")
print("我左手一式太极拳")
print("右手一剑刺身前")
print("扫腿这招叫清雪")
print("破轻功飞燕")
print("我奇筋异脉力破天")
print("一身正气荡人间")
print("除暴安良我心愿")
print("老师傅再见")
print("要想练就绝世武功")
print("就要忍受常人难忍受的痛")
print("师傅喜欢喝的茶叫做乌龙")
print("衣服爱穿中国红 师傅")
print("无论是炎夏或寒冬")
print("我都很向往山门外的天空")
print("还在南方等我 下山的我")
print("的人叫小落 来")
print("我左手一式太极拳")
print("右手一剑刺身前")
print("扫腿这招叫清雪")
print("破轻功飞燕")
print("我奇筋异脉力破天")
print("一身正气荡人间")
print("除暴安良我心愿")
print("老师傅再见")
print("人法地 地法天")
print("天法道 道法孜然")
print("师师傅 什么是孜然")
print("我左手一式太极拳")
print("右手一剑刺身前")
print("扫腿这招叫清雪")
print("破轻功飞燕")
print("我奇筋异脉力破天")
print("一身正气荡人间")
print("除暴安良我心愿")
print("老师傅再见")
while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
    screen.blit(xiashan,(0,0))
    pygame.display.update()