from os import *
from time import *
def c_spark(x,y):
    for i in range(y):
        print("\033[30m"+x)
        sleep(0.1)
        system('clear')
        print("\033[31m"+x)
        sleep(0.1)
        system('clear')
        print("\033[32m"+x)
        sleep(0.1)
        system('clear')
        print("\033[33m"+x)
        sleep(0.1)
        system('clear')    
        print("\033[34m"+x)
        sleep(0.1)
        system('clear')
        print("\033[35m"+x)
        sleep(0.1)
        system('clear')
        print("\033[36m"+x)
        sleep(0.1)
        system('clear')
        print("\033[37m"+x)
        sleep(0.1)
        system('clear')
c_spark("陈锦奕最帅",10)