from turtle import*
def Dshu(a,b,c,d,e):
    t=Turtle()
    t.penup()
    t.goto(a,b)
    t.pendown()
    t.goto(a,b-c)
    t.goto(a+d,b-c+d)
    t.goto(a+d,b-e*2-d)
    t.goto(a+d+e,b-d-e)
    t.goto(a,b)
def Dheng(a,b,c,d,e):
    t=Turtle()
    t.penup()
    t.goto(a,b)
    t.pendown()
    t.goto(a+c-e*2,b)
    t.goto(a+c-e,b+e)
    t.goto(a+c+d,b-d)
    t.goto(a+d,b-d)
    t.goto(a,b)
def Dzuodian(a,b,c):
    t=Turtle()
    t.penup()
    t.goto(a,b)
    t.pendown()
    t.rt(45)
    t.fd(c)
    t.left(150)
    t.fd(c/3)
    t.goto(a,b)
Dshu(-40,-50,200,20,5)
Dheng(-110,-130,150,10,20)
Dzuodian(0,300,200)