from turtle import *
#1、补充for循环语句，让小鱼游动起来
#2、尝试修改代码，换成其他背景、或生物

#修改代码，尝试其他海洋背景，注意文件名参考左侧。
sc = Screen()
a = Screen()
c = Screen()
e = Screen()
g = Screen()
sc.bgpic("sea.png")
sc.register_shape("fish5.png")
a.register_shape("fish1.png")
e.register_shape("潜水艇1.png")
g.register_shape("乌龟1.png")
c.register_shape("扇贝.png")
sc.register_shape("fish6.png")
a.register_shape("fish2.png")
e.register_shape("潜水艇2.png")
g.register_shape("乌龟2.png")
t = Turtle()
b = Turtle()
d = Turtle()
f = Turtle()
h = Turtle()
t.penup()
b.penup()
d.penup()
f.penup()
h.penup()
t.goto(-500,0)
b.goto(-500,100)
d.goto(0,-350)
f.goto(-500,-100)
h.goto(-500,-50)
d.shape("扇贝.png")
#在第17行补充for循环语句
#修改代码，尝试其他鱼类素材，注意文件名参考左侧。
for i in range(100):
    t.shape("fish5.png")
    b.shape("fish1.png")
    f.shape("潜水艇1.png")
    h.shape("乌龟1.png")
    t.forward(1000)
    b.forward(1000)
    f.forward(1000)
    h.forward(1000)
    t.right(180)
    b.right(180)
    f.right(180)
    h.right(180)
    t.shape("fish6.png")
    b.shape("fish2.png")
    f.shape("潜水艇2.png")
    h.shape("乌龟2.png")
    t.forward(1000)
    b.forward(1000)
    f.forward(1000)
    h.forward(1000)
    t.right(180)
    b.right(180)
    f.right(180)
    h.right(180)
